import type { Metadata } from 'next';
import {
   Montserrat,
   Montserrat_Alternates,
   Namdhinggo,
   Roboto,
   Open_Sans,
} from 'next/font/google';
import './styles/globals.css';
import './styles/normalize.css';
import Footer from './shared/layouts/Footer';
import Header from './shared/layouts/Header';
import AuthProvider from './shared/providers/AuthProvider';

const montserrat = Montserrat({
   subsets: ['latin', 'cyrillic'],
   variable: '--font-montserrat',
});

const montserratAlternates = Montserrat_Alternates({
   subsets: ['latin', 'cyrillic'],
   variable: '--font-montserrat-alternates',
   weight: ['900'],
});

const namdhinggo = Namdhinggo({
   subsets: ['latin'],
   variable: '--font-namdhinggo',
   weight: ['700', '800'],
});

const roboto = Roboto({
   subsets: ['latin', 'cyrillic'],
   variable: '--font-roboto',
   weight: ['400', '700'],
});

const openSans = Open_Sans({
   subsets: ['latin', 'cyrillic'],
   variable: '--font-open-sans',
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="uk">
         <body
            className={`${montserrat.variable} ${montserratAlternates.variable} ${namdhinggo.variable} ${roboto.variable} ${openSans.variable}`}
         >
            <AuthProvider>
               <Header />
               {children}
               <Footer />
            </AuthProvider>
         </body>
      </html>
   );
}
